version: "3"
services:
  db:
    container_name: db
    restart: always
    image: postgres
    # platform: linux/x86_64
    volumes:
      - ../../tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ruby_on_rails_sample_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
    ports:
      - "5432:5432"
    networks:
      web-db-net:

networks:
  web-db-net:
